- .gitignore
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/team_alcoholic/jumo_server/region/controller/RegionController.java
- src/main/java/team_alcoholic/jumo_server/region/domain/Region.java
- src/main/java/team_alcoholic/jumo_server/region/repository/JpaRegionRepository.java
- src/main/java/team_alcoholic/jumo_server/region/repository/RegionRepository.java
- src/main/java/team_alcoholic/jumo_server/region/service/RegionService.java
- src/main/resources/application.properties
**Jira 티켓: [BYOB-49]**
행정동 기준으로 지역 DB 구성하고, 행정동 코드(admcd) 이용해서 검색 구현함
- 법정동: 말 그대로 법률로 지정된 행정구역 단위. 1914년 지정된 이후로 변경된 적 없음.
- 행정동: 행정상 편의를 위해 지정한 행정구역 단위.
<br>
Region API 구현
- GET /region/{admcd}
- GET /region/majorList
- GET /region/subList/{admcd}
[BYOB-49]: https://swm-alcoholic.atlassian.net/browse/BYOB-49?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-49] 지역 DB 구축 및 지역 선택 관련 API 구현

- src/main/java/team_alcoholic/jumo_server/config/WebConfig.java
**Jira 티켓: [BYOB-70]**
<br>
config에 CORS 설정 관련 파일 추가
[BYOB-70]: https://swm-alcoholic.atlassian.net/browse/BYOB-70?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: CORS 설정

- build.gradle
- src/main/java/team_alcoholic/jumo_server/config/CustomAuthenticationEntryPoint.java
- src/main/java/team_alcoholic/jumo_server/config/SecurityConfig.java
- src/main/java/team_alcoholic/jumo_server/config/WebConfig.java
**Jira 티켓: [BYOB-84]**
<br>
- 로그아웃시 CORS 문제 해결
- 리다이렉션이 아닌 상태 코드를 내려주는것으로 변경
- 지역 스프링 세큐리티 권한 문제 해결
[BYOB-84]: https://swm-alcoholic.atlassian.net/browse/BYOB-84?atlOrigin=eyJpIjoiZDE4MjBiYjE1OWQ2NDlkMThkNDBmYjlmNDU1MTZkZmYiLCJwIjoiaiJ9
> [BYOB-84] 로그아웃 CORS 문제 및 지역 권한 문제 해결

- .gitignore
- Dockerfile
- gradle/wrapper/gradle-wrapper.properties
**Jira 티켓: [BYOB-91]**
<br>
- 백엔드 dev cicd 구현을 위한 도커 파일 추가
[BYOB-91]: https://swm-alcoholic.atlassian.net/browse/BYOB-91?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-91] 백엔드 dev ci/cd 구축

- src/main/java/team_alcoholic/jumo_server/config/SecurityConfig.java
- src/main/java/team_alcoholic/jumo_server/config/WebConfig.java
**Jira 티켓: [BYOB-95]**
<br>
- aseurl 환경변수 미지정 해결
[BYOB-95]: https://swm-alcoholic.atlassian.net/browse/BYOB-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  [BYOB-95] baseurl 환경변수 미지정 해결

- src/main/java/team_alcoholic/jumo_server/meeting/domain/Meeting.java
- src/main/java/team_alcoholic/jumo_server/meeting/dto/MeetingListDto.java
- src/main/java/team_alcoholic/jumo_server/meeting/repository/JpaMeetingRepository.java
**Jira 티켓: [BYOB-92]**
<br>
지역목록조회 API 요청 시 region에 지역코드를 담아서 응답하는 문제 해결
[BYOB-92]: https://swm-alcoholic.atlassian.net/browse/BYOB-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-92] 지역목록조회 API 요청 시 region에 지역코드를 담아서 응답하는 문제 해결

- .gitignore
- src/main/java/team_alcoholic/jumo_server/JumoServerApplication.java
- src/main/java/team_alcoholic/jumo_server/common/domain/BaseEntity.java
- src/main/java/team_alcoholic/jumo_server/common/domain/BaseTimeEntity.java
- src/main/java/team_alcoholic/jumo_server/meeting/domain/Meeting.java
- src/main/java/team_alcoholic/jumo_server/meeting/domain/MeetingImage.java
- src/main/java/team_alcoholic/jumo_server/region/domain/Region.java
- src/main/java/team_alcoholic/jumo_server/user/domain/User.java
**Jira 티켓: [BYOB-103]**
<br>
- CreatedDate, LastModifiedDate 공통 엔티티 추가 후 모든 엔티티에 적용
[BYOB-103]: https://swm-alcoholic.atlassian.net/browse/BYOB-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-103] 공통 엔티티 구현

- .github/workflows/backend_dev.yml
- .gitignore
**Jira 티켓: [BYOB-106]**
<br>
- docker hub  대신 ecr 사용하도록 변경
[BYOB-106]: https://swm-alcoholic.atlassian.net/browse/BYOB-106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-106] 도커 이미지 application.properties 노출 문제 해결

- .github/workflows/backend_dev.yml
**Jira 티켓: [BYOB-107]**
<br>
- ecr 임시 토큰 발급 받도록 수정
[BYOB-107]: https://swm-alcoholic.atlassian.net/browse/BYOB-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-107] ecr 권한 문제 해결

- src/main/java/team_alcoholic/jumo_server/domain/meeting/repository/JpaMeetingRepository.java
**Jira 티켓: [BYOB-124]**
<br>
Meeting repository에서 패키지 구조 변경에 따라 발생한 JPQL 오류 해결
[BYOB-124]: https://swm-alcoholic.atlassian.net/browse/BYOB-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-124] Meeting repository에서 패키지 구조 변경에 따라 발생한 JPQL 오류 해결

- .github/workflows/backend_dev.yml
- .gitignore
- Dockerfile
- src/main/resources/application-dev.properties
- src/main/resources/application-local.properties
- src/main/resources/application.properties
**Jira 티켓: [BYOB-128]**
<br>
환경변수 설정 방식 변경에 따라 workflow/dockerfile 변경 및 properties 파일들 추가
[BYOB-128]: https://swm-alcoholic.atlassian.net/browse/BYOB-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-128] CI/CD 환경변수 적용 방식 변경

- src/main/resources/logback-config.xml
- src/main/resources/logback-spring.xml
**Jira 티켓: [BYOB-139]**
<br>
console에서의 로그가 cloudwatch에서의 로그보다 자세하게 출력될 수 있도록 분리
[BYOB-139]: https://swm-alcoholic.atlassian.net/browse/BYOB-139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-139] log 출력이 cloudwatch 및 console에도 발생하도록 변경

- src/main/java/team_alcoholic/jumo_server/domain/meeting/repository/MeetingRepository.java
**Jira 티켓: [BYOB-147]**
<br>
- region null처리 문제 해결
[BYOB-147]: https://swm-alcoholic.atlassian.net/browse/BYOB-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-147] region null처리 문제 해결

- .github/workflows/backend_prod.yml
**Jira 티켓: [BYOB-150]**
<br>
production workflow에 develop 컨테이너 이미지 받아오는 버그 해결
[BYOB-150]: https://swm-alcoholic.atlassian.net/browse/BYOB-150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-150] production workflow에 develop 컨테이너 이미지 받아오는 버그 해결

- src/main/java/team_alcoholic/jumo_server/domain/meeting/controller/MeetingApi.java
- src/main/java/team_alcoholic/jumo_server/domain/meeting/controller/MeetingController.java
- src/main/java/team_alcoholic/jumo_server/domain/meeting/repository/MeetingRepository.java
- src/main/java/team_alcoholic/jumo_server/domain/meeting/service/MeetingService.java
**Jira 티켓: [BYOB-154]**
<br>
- 모임 목록 주종 필터 기능 추가
[BYOB-154]: https://swm-alcoholic.atlassian.net/browse/BYOB-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-154] 모임목록 필터 API 구현

- build.gradle
- src/main/java/team_alcoholic/jumo_server/JumoServerApplication.java
- src/main/java/team_alcoholic/jumo_server/domain/liquorsearch/controller/LiquorSearchController.java
- src/main/java/team_alcoholic/jumo_server/domain/liquorsearch/domain/Liquor.java
- src/main/java/team_alcoholic/jumo_server/domain/liquorsearch/service/LiquorSearchService.java
- src/main/java/team_alcoholic/jumo_server/global/config/OpenSearchConfig.java
- src/main/java/team_alcoholic/jumo_server/global/config/WebConfig.java
- src/main/resources/application-dev.properties
- src/main/resources/application-local.properties
- src/main/resources/application-prod.properties
**Jira 티켓: [BYOB-161]**
<br>
AWS OpenSearch Service 기반의 주류 검색 API 구현
- AWS OpenSearch Service에 주류 데이터셋 업로드
- OpenSearch Java Client를 사용해서 SpringBoot와 OpenSearch 연동
- 키워드 기반의 주류 검색 API 구현
[BYOB-161]: https://swm-alcoholic.atlassian.net/browse/BYOB-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-161] 주류 검색 API 구현

- src/main/java/team_alcoholic/jumo_server/domain/liquor/dto/LiquorResDto.java
- src/main/java/team_alcoholic/jumo_server/domain/liquorsearch/controller/LiquorSearchController.java
- src/main/java/team_alcoholic/jumo_server/domain/liquorsearch/domain/LiquorES.java
- src/main/java/team_alcoholic/jumo_server/domain/liquorsearch/service/LiquorSearchService.java
**Jira 티켓: [BYOB-167]**
<br>
- LiquorES 엔티티 필드 수정
- Liquor 응답 객체에 enName 필드 추가: 프론트에서 필요해용
[BYOB-167]: https://swm-alcoholic.atlassian.net/browse/BYOB-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-167] 주류 데이터 구조 변경에 따른 관련 코드 수정

- src/main/java/team_alcoholic/jumo_server/domain/tastingnote/controller/TastingNoteController.java
- src/main/java/team_alcoholic/jumo_server/domain/tastingnote/dto/TastingNoteListResDTO.java
- src/main/java/team_alcoholic/jumo_server/domain/tastingnote/repository/TastingNoteRepository.java
- src/main/java/team_alcoholic/jumo_server/domain/tastingnote/service/TastingNoteService.java
**Jira 티켓: [BYOB-171]**
<br>
- 주류 id를 받아, 이에 해당하는 테이스팅 리뷰 목록을 최신순으로 응답하는 API 구현
- 구체적인 작성자 정보를 표시할 수 있도록 `TastingNoteListResDTO` 생성
[BYOB-171]: https://swm-alcoholic.atlassian.net/browse/BYOB-171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-171] 주류 테이스팅 리뷰 목록 API 구현

- src/main/java/team_alcoholic/jumo_server/domain/tastingnote/controller/TastingNoteController.java
- src/main/java/team_alcoholic/jumo_server/domain/tastingnote/dto/TastingNoteResDTO.java
- src/main/java/team_alcoholic/jumo_server/domain/user/controller/UserController.java
- src/main/java/team_alcoholic/jumo_server/global/config/GetRedirectUrlFilter.java
- src/main/java/team_alcoholic/jumo_server/global/config/SecurityConfig.java
**Jira 티켓: [BYOB-173]**
<br>
- 로그인 시 기존 로그인으로 가게 설정
- 스프링 세큐리티에서 맨 처음 오는 요청을 가로챈다음 이를 redirecturl에 세션으로 넣어둠
[BYOB-173]: https://swm-alcoholic.atlassian.net/browse/BYOB-173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-173] 백엔드 로그인 리다이렉션 처리

- src/main/resources/application-dev.properties
- src/main/resources/application-prod.properties
**Jira 티켓: [BYOB-177]**
<br>
- spring ai application.properties dev,prod 반영
[BYOB-177]: https://swm-alcoholic.atlassian.net/browse/BYOB-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-177] spring ai application.properties dev,prod 반영

- build.gradle
- src/main/java/team_alcoholic/jumo_server/domain/auth/dto/CustomOAuth2User.java
- src/main/java/team_alcoholic/jumo_server/domain/liquorsearch/service/LiquorSearchService.java
- src/main/java/team_alcoholic/jumo_server/domain/tastingnote/dto/TastingNoteListResDTO.java
- src/main/java/team_alcoholic/jumo_server/domain/tastingnote/dto/TastingNoteResDTO.java
- src/main/java/team_alcoholic/jumo_server/domain/user/domain/User.java
- src/main/java/team_alcoholic/jumo_server/domain/user/dto/UserDTO.java
- src/main/java/team_alcoholic/jumo_server/domain/user/service/UserService.java
- src/main/java/team_alcoholic/jumo_server/global/config/GetRedirectUrlFilter.java
- src/main/resources/application-dev.properties
- src/main/resources/application-local.properties
- src/main/resources/application-prod.properties
**Jira 티켓: [BYOB-180]**
<br>
**작업 사항**
- 세션 레디스에 저장
- 처음 가입시 닉네임 프로필 사진 랜덤으로 생성되게 함
[BYOB-180]: https://swm-alcoholic.atlassian.net/browse/BYOB-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-180] 로그인 레디스 연결 및 정책 변경

- src/main/java/team_alcoholic/jumo_server/domain/tastingnote/controller/TastingNoteController.java
- src/main/java/team_alcoholic/jumo_server/domain/tastingnote/repository/TastingNoteRepository.java
- src/main/java/team_alcoholic/jumo_server/domain/tastingnote/service/TastingNoteService.java
- src/main/resources/application-local.properties
**Jira 티켓: [BYOB-185]**
<br>
마이페이지에서 사용자의 테이스팅노트 목록을 보여주기 위한, 사용자별 테이스팅노트 목록 API를 구현함
[BYOB-185]: https://swm-alcoholic.atlassian.net/browse/BYOB-185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-185] 사용자별 테이스팅노트 목록 API 구현

- src/main/java/team_alcoholic/jumo_server/domain/health/HealthCheckController.java
**Jira 티켓: [BYOB-189]**
<br>
**작업 사항**
- 헬스 체크용 api 구현
[BYOB-189]: https://swm-alcoholic.atlassian.net/browse/BYOB-189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-189]: 헬스 체크용 api 구현

- src/main/resources/logback-spring.xml
**Jira 티켓: [BYOB-188]**
<br>
CloudWatch Log Appender에 대한 설정을 변경함
- pattern을 console pattern에서 file pattern으로 변경
- maxFlushTime을 30분으로 변경
[BYOB-188]: https://swm-alcoholic.atlassian.net/browse/BYOB-188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-188] CloudWatch Log Appender 설정 변경

- src/main/java/team_alcoholic/jumo_server/domain/liquorsearch/service/LiquorSearchService.java
**Jira 티켓: [BYOB-164]**
<br>
OpenSearch tokenizer 변경에 따른 query 수정 및 개선
[BYOB-164]: https://swm-alcoholic.atlassian.net/browse/BYOB-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-164] OpenSearch tokenizer 변경에 따른 query 수정 및 개선

- src/main/java/team_alcoholic/jumo_server/domain/liquor/controller/LiquorController.java
- src/main/java/team_alcoholic/jumo_server/domain/liquor/domain/Liquor.java
- src/main/java/team_alcoholic/jumo_server/domain/liquor/dto/LiquorPostDto.java
- src/main/java/team_alcoholic/jumo_server/domain/liquor/dto/LiquorResDto.java
- src/main/java/team_alcoholic/jumo_server/domain/liquor/service/LiquorService.java
- src/main/resources/application-dev.properties
- src/main/resources/application-local.properties
- src/main/resources/application-prod.properties
**Jira 티켓: [BYOB-197]**
<br>
- 주류 추가 api 구현
- 세션 24시간으로 연장
[BYOB-197]: https://swm-alcoholic.atlassian.net/browse/BYOB-197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-197] 주류 추가 api

- src/main/java/team_alcoholic/jumo_server/global/config/GetRedirectUrlFilter.java
**Jira 티켓: [BYOB-200]**
<br>
- 신규 가입자 로그인 후 뒤로 가면 서버 오류 페이지로 넘어가는 버그 해결
[BYOB-200]: https://swm-alcoholic.atlassian.net/browse/BYOB-200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-200] 신규 가입자 로그인 후 뒤로 가면 서버 오류 페이지로 넘어가는 버그 해결

- src/main/java/team_alcoholic/jumo_server/v2/note/dto/response/NoteRes.java
- src/main/java/team_alcoholic/jumo_server/v2/note/dto/response/PurchaseNoteRes.java
- src/main/java/team_alcoholic/jumo_server/v2/note/dto/response/TastingNoteRes.java
- src/main/resources/application-local.properties
**[BYOB-224]**
<br>
Note 도메인 API 응답 시 createdAt/updatedAt 누락된 문제 해결
[BYOB-224]: https://swm-alcoholic.atlassian.net/browse/BYOB-224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-224] Note 도메인 API 응답 시 createdAt/updatedAt 누락된 문제 해결

- src/main/java/team_alcoholic/jumo_server/v1/auth/service/OAuth2UserService.java
- src/main/java/team_alcoholic/jumo_server/v2/aroma/controller/AromaController.java
- src/main/java/team_alcoholic/jumo_server/v2/aroma/domain/Aroma.java
- src/main/java/team_alcoholic/jumo_server/v2/aroma/dto/AromaCreateReq.java
- src/main/java/team_alcoholic/jumo_server/v2/aroma/repository/AromaCategoryRepository.java
- src/main/java/team_alcoholic/jumo_server/v2/aroma/repository/AromaRepository.java
- src/main/java/team_alcoholic/jumo_server/v2/aroma/service/AromaService.java
- src/main/java/team_alcoholic/jumo_server/v2/liquor/controller/NewLiquorController.java
- src/main/java/team_alcoholic/jumo_server/v2/liquor/domain/LiquorAroma.java
- src/main/java/team_alcoholic/jumo_server/v2/liquor/domain/LiquorCategory.java
- src/main/java/team_alcoholic/jumo_server/v2/liquor/domain/NewLiquor.java
- src/main/java/team_alcoholic/jumo_server/v2/liquor/dto/LiquorCategoryRes.java
- src/main/java/team_alcoholic/jumo_server/v2/liquor/dto/LiquorRes.java
- src/main/java/team_alcoholic/jumo_server/v2/liquor/repository/NewLiquorRepository.java
- src/main/java/team_alcoholic/jumo_server/v2/liquor/service/NewLiquorService.java
- src/main/java/team_alcoholic/jumo_server/v2/note/controller/NoteController.java
- src/main/java/team_alcoholic/jumo_server/v2/note/repository/NoteRepository.java
- src/main/java/team_alcoholic/jumo_server/v2/note/service/NoteService.java
- src/main/java/team_alcoholic/jumo_server/v2/user/dto/UserUpdateReq.java
- src/main/java/team_alcoholic/jumo_server/v2/user/service/UserService.java
**[BYOB-226]**
<br>
사용자의 주류별 노트 목록 조회 API 구현
OAuth2 과정에 사용되는 userService를 v1에서 v2로 변경
LiquorAroma 엔티티 생성과 관련해서, 주류 상세조회 API를 일부 수정
아로마를 직접 추가하는 API 구현
[BYOB-226]: https://swm-alcoholic.atlassian.net/browse/BYOB-226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BYOB-226] 업데이트 관련 각종 API 추가 및 수정
